action_selector: epsilon_greedy
adv_hypernet_embed: 64
adv_hypernet_layers: 1
agent: rnn
agent_output_type: q
attend_reg_coef: 0.001
batch_size: 32
batch_size_run: 1
buffer_cpu_only: true
buffer_size: 5000
burn_in_period: 100
checkpoint_path: ''
double_q: true
env: gymma
env_args:
  key: Foraging-10x10-3p-3f-v2
  pretrained_wrapper: null
  time_limit: 25
epsilon_anneal_time: 50000
epsilon_finish: 0.05
epsilon_start: 1.0
evaluate: false
evaluation_epsilon: 0.0
gamma: 0.99
grad_norm_clip: 10
hidden_dim: 128
hypergroup: hp_grp_24
hypernet_embed: 64
is_adv_attention: true
is_minus_one: true
is_stop_gradient: true
label: default_label
learner: dmaq_qatten_learner
learner_log_interval: 10000
load_step: 0
local_results_path: results
log_interval: 25000
lr: 0.0003
mac: basic_mac
mask_dead: false
mixer: dmaq_qatten
mixing_embed_dim: 32
n_head: 4
name: qplex_best_conf_0
nonlinear: false
num_kernel: 4
obs_agent_id: true
obs_last_action: true
optim_alpha: 0.99
optim_eps: 1.0e-05
repeat_id: 1
runner: episode
runner_log_interval: 10000
save_model: false
save_model_interval: 50000
save_replay: false
state_bias: true
t_max: 2050000
target_update_interval: 200
test_greedy: true
test_interval: 25000
test_nepisode: 100
unit_dim: 5
use_cuda: false
use_rnn: true
use_tensorboard: false
weighted_head: false
